In [3]:
!pip install pandas
!pip install numpy
import pandas as pd
import numpy as np
import sqlite3

'pip' is not recognized as an internal or external command,
operable program or batch file.

'pip' is not recognized as an internal or external command,
operable program or batch file.

ModuleNotFoundError: No module named 'pandas'

In [2]:
data = pd.read_csv('student_mh_data.csv')
data

FileNotFoundError: [Errno 2] No such file or directory: 'student_mh_data.csv'

In [ ]:
!pip install ipython-sql

In [34]:
cnn = sqlite3.connect('database.db')

In [44]:
data.to_sql('students', cnn)

286

In [37]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [38]:
%sql sqlite:///database.db

In [45]:
%%sql
SELECT *
FROM students
LIMIT 10

   sqlite://
   sqlite:///data.db
 * sqlite:///database.db
Done.

[(0, 'Inter', 'SEA', 'Male', 'Grad', 24.0, 4.0, 5.0, 'Long', 3.0, 'Average', 5.0, 'High', None, 'Yes', 'No', 'No', 'No', 0.0, 'Min', 34.0, 23.0, 9.0, 11.0, 8.0, 11.0, 2.0, 27.0, 91.0, 5.0, 5.0, 6.0, 3.0, 2.0, 1.0, 4.0, 1.0, 3.0, 4.0, None, 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'),
 (1, 'Inter', 'SEA', 'Male', 'Grad', 28.0, 5.0, 1.0, 'Short', 4.0, 'High', 4.0, 'High', None, 'No', 'No', 'No', 'No', 2.0, 'Min', 48.0, 8.0, 7.0, 5.0, 4.0, 3.0, 2.0, 10.0, 39.0, 7.0, 7.0, 7.0, 4.0, 4.0, 4.0, 4.0, 1.0, 1.0, 1.0, None, 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'),
 (2, 'Inter', 'SEA', 'Male', 'Grad', 25.0, 4.0, 6.0, 'Long', 4.0, 'High', 4.0, 'High', 'Yes', 'Yes', 'No', 'No', 'No', 2.0, 'Min', 41.0, 13.0, 4.0, 7.0, 6.0, 4.0, 3.0, 14.0, 51.0, 3.0, 3.0, 3.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, None, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'),
 (3, 'Inter', 'EA', 'Female', 'Grad', 29.0, 5.0, 1.0, 'Short', 2.0, 'Low', 3.0, 'Average', 'No', 'No', 'No', 'No', 'No', 3.0, 'Min', 37.0, 16.0, 10.0, 10.0, 8.0, 6.0, 4.0, 21.0, 75.0, 5.0, 5.0, 5.0, 5.0, 5.0, 2.0, 2.0, 2.0, 4.0, 4.0, None, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No'),
 (4, 'Inter', 'EA', 'Female', 'Grad', 28.0, 5.0, 1.0, 'Short', 1.0, 'Low', 3.0, 'Average', 'Yes', 'No', 'No', 'No', 'No', 3.0, 'Min', 37.0, 15.0, 12.0, 5.0, 8.0, 7.0, 4.0, 31.0, 82.0, 5.0, 5.0, 5.0, 2.0, 5.0, 2.0, 5.0, 5.0, 4.0, 4.0, None, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No'),
 (5, 'Inter', 'SEA', 'Male', 'Grad', 24.0, 4.0, 6.0, 'Long', 3.0, 'Average', 4.0, 'High', 'Yes', 'No', 'No', 'No', 'No', 6.0, 'Mild', 38.0, 18.0, 8.0, 10.0, 8.0, 7.0, 3.0, 29.0, 83.0, 6.0, 5.0, 4.0, 2.0, 1.0, 1.0, 2.0, 1.0, 5.0, 1.0, None, 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No'),
 (6, 'Inter', 'SA', 'Male', 'Grad', 23.0, 4.0, 1.0, 'Short', 3.0, 'Average', 5.0, 'High', 'Yes', 'No', 'No', 'No', 'No', 3.0, 'Min', 46.0, 17.0, 6.0, 10.0, 5.0, 3.0, 2.0, 15.0, 58.0, 7.0, 5.0, 7.0, 2.0, 2.0, 1.0, 5.0, 1.0, 1.0, 1.0, None, 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No'),
 (7, 'Inter', 'SEA', 'Female', 'Grad', 30.0, 5.0, 2.0, 'Medium', 1.0, 'Low', 1.0, 'Low', 'Yes', 'Yes', 'Yes', 'No', 'No', 9.0, 'Mild', 41.0, 16.0, 20.0, 19.0, 15.0, 11.0, 6.0, 40.0, 127.0, 7.0, 2.0, 2.0, 2.0, 6.0, 2.0, 1.0, 1.0, 3.0, 1.0, None, 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No'),
 (8, 'Inter', 'SEA', 'Female', 'Grad', 25.0, 4.0, 4.0, 'Long', 4.0, 'High', 4.0, 'High', 'No', 'No', 'No', 'Yes', 'Other', 7.0, 'Mild', 36.0, 22.0, 12.0, 13.0, 13.0, 10.0, 6.0, 33.0, 109.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, None, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'),
 (9, 'Inter', 'Others', 'Male', 'Grad', 31.0, 5.0, 2.0, 'Medium', 1.0, 'Low', 4.0, 'High', 'Yes', 'Yes', 'No', 'No', 'No', 3.0, 'Min', 48.0, 8.0, 4.0, 5.0, 12.0, 3.0, 2.0, 17.0, 51.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, None, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No')]

In [46]:
%%sql
SELECT COUNT(*) total_records
FROM students

   sqlite://
   sqlite:///data.db
 * sqlite:///database.db
Done.

[(286,)]